// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCFKPGCBjCnz9yKqS0qhSHI__FKjFU9Q',
    appId: '1:662960687375:web:e302cbbd8d2e3b53aad67a',
    messagingSenderId: '662960687375',
    projectId: 'intelizia-gamezi',
    authDomain: 'intelizia-gamezi.firebaseapp.com',
    storageBucket: 'intelizia-gamezi.firebasestorage.app',
    measurementId: 'G-QG9S8YQQXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5w6VVERgqZpn3Rq4ONHk1W6qfWuhCMM',
    appId: '1:662960687375:android:8df106d3a44d6d5faad67a',
    messagingSenderId: '662960687375',
    projectId: 'intelizia-gamezi',
    storageBucket: 'intelizia-gamezi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtRgDdea8eMBS3RSfptciWnILXVA02-44',
    appId: '1:662960687375:ios:6c502cc94fad7ae5aad67a',
    messagingSenderId: '662960687375',
    projectId: 'intelizia-gamezi',
    storageBucket: 'intelizia-gamezi.firebasestorage.app',
    iosBundleId: 'com.example.gamezi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtRgDdea8eMBS3RSfptciWnILXVA02-44',
    appId: '1:662960687375:ios:6c502cc94fad7ae5aad67a',
    messagingSenderId: '662960687375',
    projectId: 'intelizia-gamezi',
    storageBucket: 'intelizia-gamezi.firebasestorage.app',
    iosBundleId: 'com.example.gamezi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkCFKPGCBjCnz9yKqS0qhSHI__FKjFU9Q',
    appId: '1:662960687375:web:dcb098497eb416d9aad67a',
    messagingSenderId: '662960687375',
    projectId: 'intelizia-gamezi',
    authDomain: 'intelizia-gamezi.firebaseapp.com',
    storageBucket: 'intelizia-gamezi.firebasestorage.app',
    measurementId: 'G-JWC25L60DD',
  );
}
